### index
GET http://localhost:8080/api/products?page=3&per_page=1
Accept: application/json
Authorization: Bearer rHWftReTmcyTHf0SjCR

### show
GET http://localhost:8080/api/products/1
Authorization: Bearer rHWftReTmcyTHf0SjCR

### create
POST http://localhost:8080/api/products
Authorization: Bearer rHWftReTmcyTHf0SjCR
Content-Type: application/json

{
  "nama": "Yoga Slim 7i Aura Edition",
  "harga": 15000000,
  "jumlah": 10
}

### update all field
PUT http://localhost:8080/api/products/5
Authorization: Bearer rHWftReTmcyTHf0SjCR
Content-Type: application/json

{
  "nama": "Yoga Slim 7i Aura Editions",
  "harga": 25000000,
  "jumlah": 20
}

### update some field
PATCH http://localhost:8080/api/products/5
Authorization: Bearer rHWftReTmcyTHf0SjCR
Content-Type: application/json

{ 
  "jumlah": 25
}

### delete
DELETE http://localhost:8080/api/products/5
Authorization: Bearer rHWftReTmcyTHf0SjCR